### ISSUE TITLE
Use WiiBrew Mobile edition for website

### ISSUE THREAD

**Issue by wuniversales** [RiiConnect24/Internet-Channel-Bookmarks#3]
WiiBrew Mobile edition link: https://wiibrew.org/w/?title=Main_Page&mobileaction=toggle_view_mobile

**Comment by ghost** [comment]
Does it really need to be the mobile link though?

**Comment by Peter0x44** [comment]
Does this really make a difference with viewing on the wii? I doubt it would work either way but it would be nice to test.

**Comment by Peter0x44** [comment]
It makes zero difference as far as I can tell. 
![hhh](https://user-images.githubusercontent.com/49879065/79886953-79110a80-83e9-11ea-

**Comment by urmum-69** [comment]
It makes zero difference as far as I can tell. 
![hhh](https://user-images.githubusercontent.com/49879065/79886953-79110a80-83e9-11ea-

**Comment by Artuto** [comment]
That image doesnt even exist
