### ISSUE TITLE
Add wikipedia (Mobile edition)

### ISSUE THREAD

**Issue by wuniversales** [RiiConnect24/Internet-Channel-Bookmarks#4]
Spanish version: https://es.m.wikipedia.org
English version: https://en.m.wikipedia.org
Deutsch version: https://de.m.wikipedia.org
Francais version: https://fr.m.wikipedia.org
And more... 

You can see all language available here
https://www.wikipedia.org/

Only add (code country).m.wikipedia.org

**Comment by ghost** [comment]
Again, why do they need to add the mobile version? Wikipedia already detects mobile devices when visiting the site, so there's no need.

**Comment by Peter0x44** [comment]
I doubt the mobile version of wikipedia would work on the internet channel anyway. I'd prefer if you'd test if it actually made a difference first.
