### ISSUE TITLE
Add Spanish translation

### ISSUE THREAD

**Issue by wuniversales** [RiiConnect24/Internet-Channel-Bookmarks#9]
https://github.com/RiiConnect24/Internet-Channel-Bookmarks/pull/8

**Comment by Peter0x44** [comment]
why open a pr *and* an issue? just one is sufficient

**Comment by wuniversales** [comment]
I don't know if github reports the "pull request".
At least, some developers have seen them say add an "issue", to find out they have a "pull request".
